### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sangjunp4rk** [chesare40/Colmar#5]
Summary Grade: Needs Improvements

Good job with your code! I really like the use of indentation and whitespace in your html code! Makes your code very easy to read! Also, good decisions on the classes and ids name. It makes it very clear what its purpose is and makes grouping your sections very effective. These organizational skills come in handy as you expand your code. Great start to the Ready program!

I included a few notes in both the html and css files for you to think more critically about. Make sure to add mobile resizing. The most important thing is to add mobile resizing. I know that it can be tedious, but you should try to add mobile resizing so you control how your website looks even on different mobile screens. Some suggestions would be to decrease the size of the images when the screen size decreases or rearrange the layout of the text and images so you don’t have to scroll horizontally to read everything.

**Comment by chesare40** [comment]
Dear Sang,

Thank you very much for your feedback. I will work on mobile resizing and follow your comments.

Thanks.

Cesar.
